<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate table first to avoid duplicates if run multiple times
        Menu::truncate();

        $menus = [
            [
                'id' => 3,
                'name' => 'Pembelajaran',
                'type' => 'category',
                'content' => null,
                'url' => '#',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => null,
                'parent_id' => null,
                'order' => 2,
            ],
            [
                'id' => 4,
                'name' => 'Mata Kuliah Saya',
                'type' => 'link',
                'content' => null,
                'url' => 'learning.courses',
                'icon' => 'fa-solid fa-book-open',
                'permission_name' => 'view_menu_4',
                'parent_id' => 3,
                'order' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Aktivitas Pembelajaran',
                'type' => 'link',
                'content' => null,
                'url' => 'learning.activities',
                'icon' => 'fa-regular fa-calendar',
                'permission_name' => 'view_menu_5',
                'parent_id' => 3,
                'order' => 2,
            ],
            [
                'id' => 6,
                'name' => 'Evaluasi',
                'type' => 'link',
                'content' => null,
                'url' => 'learning.evaluations',
                'icon' => 'fa-solid fa-clipboard-check',
                'permission_name' => 'view_menu_6',
                'parent_id' => 3,
                'order' => 3,
            ],
            [
                'id' => 7,
                'name' => 'Laporan',
                'type' => 'link',
                'content' => null,
                'url' => 'learning.reports',
                'icon' => 'fa-solid fa-file-lines',
                'permission_name' => 'view_menu_7',
                'parent_id' => 3,
                'order' => 4,
            ],
            [
                'id' => 8,
                'name' => 'Administrasi Platform',
                'type' => 'category',
                'content' => null,
                'url' => '#',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => null,
                'parent_id' => null,
                'order' => 3,
            ],
            [
                'id' => 9,
                'name' => 'Manajemen Pengguna',
                'type' => 'link',
                'content' => null,
                'url' => '#',
                'icon' => 'fa-solid fa-layer-group',
                'permission_name' => 'view_menu_9',
                'parent_id' => 8,
                'order' => 1,
            ],
            [
                'id' => 10,
                'name' => 'Daftar Pengguna',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.users.index',
                'icon' => 'fa-solid fa-book',
                'permission_name' => 'view_menu_10',
                'parent_id' => 9,
                'order' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Daftar Role',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.roles.index',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_11',
                'parent_id' => 9,
                'order' => 2,
            ],
            [
                'id' => 12,
                'name' => 'Tambah Pengguna',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.user.create',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_12',
                'parent_id' => 9,
                'order' => 3,
            ],
            [
                'id' => 13,
                'name' => 'Manajemen Mata Kuliah',
                'type' => 'link',
                'content' => null,
                'url' => '#',
                'icon' => 'fa-solid fa-folder-open',
                'permission_name' => 'view_menu_13',
                'parent_id' => 8,
                'order' => 2,
            ],
            [
                'id' => 14,
                'name' => 'Daftar Mata Kuliah',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.courses.index',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_14',
                'parent_id' => 13,
                'order' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Daftar Sesi',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.enroll.create',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_15',
                'parent_id' => 13,
                'order' => 2,
            ],
            [
                'id' => 16,
                'name' => 'Kategori Sesi',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.session-categories.index',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_16',
                'parent_id' => 13,
                'order' => 3,
            ],
            [
                'id' => 17,
                'name' => 'Pengaturan Platform',
                'type' => 'link',
                'content' => null,
                'url' => '#',
                'icon' => 'fa-solid fa-gear',
                'permission_name' => 'view_menu_17',
                'parent_id' => 8,
                'order' => 3,
            ],
            [
                'id' => 18,
                'name' => 'Laporan Platform',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.reports.index',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_18',
                'parent_id' => 17,
                'order' => 1,
            ],
            [
                'id' => 19,
                'name' => 'Manajemen Menu',
                'type' => 'link',
                'content' => null,
                'url' => 'admin.menus.index',
                'icon' => 'fa-solid fa-circle',
                'permission_name' => 'view_menu_19',
                'parent_id' => 17,
                'order' => 2,
            ],
            [
                'id' => 25,
                'name' => 'birjon',
                'type' => 'article',
                'content' => null,
                'url' => '/channel/25',
                'icon' => 'fa-solid fa-headphones',
                'permission_name' => 'view_menu_25',
                'parent_id' => null,
                'order' => 4,
            ],
        ];

        foreach ($menus as $menu) {
            Menu::create($menu);
        }
    }
}
